// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuNgxr5QU1BS2Y0Ms0vnGG9TJJTEPhQQs',
    appId: '1:1005918606004:web:a4e4d4c058f4c49625fde1',
    messagingSenderId: '1005918606004',
    projectId: 'fasum-app-7f258',
    authDomain: 'fasum-app-7f258.firebaseapp.com',
    storageBucket: 'fasum-app-7f258.firebasestorage.app',
    measurementId: 'G-WMZSZDD04H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmonEvwXXL53VHqd8cZmZZRvysIYetlUE',
    appId: '1:1005918606004:android:d4c4b8a89315f05825fde1',
    messagingSenderId: '1005918606004',
    projectId: 'fasum-app-7f258',
    storageBucket: 'fasum-app-7f258.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7ZrecdcBwVdr0ES4MFXYt1OZ9RCeitHA',
    appId: '1:1005918606004:ios:821826c625e9819525fde1',
    messagingSenderId: '1005918606004',
    projectId: 'fasum-app-7f258',
    storageBucket: 'fasum-app-7f258.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7ZrecdcBwVdr0ES4MFXYt1OZ9RCeitHA',
    appId: '1:1005918606004:ios:821826c625e9819525fde1',
    messagingSenderId: '1005918606004',
    projectId: 'fasum-app-7f258',
    storageBucket: 'fasum-app-7f258.firebasestorage.app',
    iosBundleId: 'com.example.fasum',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuNgxr5QU1BS2Y0Ms0vnGG9TJJTEPhQQs',
    appId: '1:1005918606004:web:0a1282b056ae0c5525fde1',
    messagingSenderId: '1005918606004',
    projectId: 'fasum-app-7f258',
    authDomain: 'fasum-app-7f258.firebaseapp.com',
    storageBucket: 'fasum-app-7f258.firebasestorage.app',
    measurementId: 'G-538DM7PY66',
  );
}
